// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, username)
VALUES ($1, $2, $3)
RETURNING id, name, email, username, verified
`

type CreateUserParams struct {
	Name     string
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO "verification" (user_id, code) 
VALUES ($1, $2)
RETURNING user_id, code, created_at
`

type CreateVerificationParams struct {
	UserID uuid.UUID
	Code   int32
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRowContext(ctx, createVerification, arg.UserID, arg.Code)
	var i Verification
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, username, verified FROM "user" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, name, email, username, verified FROM "user" WHERE email = $1 OR username = $2
`

type GetUserByEmailOrUsernameParams struct {
	Email    string
	Username string
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, username, verified FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, email, username, verified FROM "user" WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const getVerificationByUser = `-- name: GetVerificationByUser :one
SELECT user_id, code, created_at FROM "verification" WHERE user_id = $1
ORDER BY "created_at" DESC
LIMIT 1
`

func (q *Queries) GetVerificationByUser(ctx context.Context, userID uuid.UUID) (Verification, error) {
	row := q.db.QueryRowContext(ctx, getVerificationByUser, userID)
	var i Verification
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user" SET 
"name" = COALESCE($1, name),
email = COALESCE($2, email),
username = COALESCE($3, username),
verified = COALESCE($4, verified)
WHERE id = $5
RETURNING id, name, email, username, verified
`

type UpdateUserParams struct {
	Name     string
	Email    string
	Username string
	Verified sql.NullBool
	ID       uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.Verified,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Verified,
	)
	return i, err
}
